### ISSUE TITLE
CSS design does not work on iOS Web -  looks broken

### ISSUE THREAD

**Issue by buzzcosm** [buzzcosm/calculator-vanilla-js-app#1]
The simulation in the web browser on the PC works well:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e6de12aa-e444-4f1d-a6a9-dbf67a182175">

but on iOS in web looks broken:

<img width="355" alt="image" src="https://github.com/user-attachments/assets/71285d38-86a8-4402-bfe2-7dc17b555c89">

**Comment by buzzcosm** [comment]
Wrong sized on my exercise:

```css
.operator {
  /* other styles */
  font-size: 30px; /* old: 40px */
}
```
